name: Generete release

on: workflow_dispatch

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: webcardinal-workspace_node-modules
        with:
          path: ./webcardinal-workspace/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./webcardinal-workspace/package-lock.json') }}-v2

      - name: Install
        run: npm install && npm run clean
        shell: bash

      - name: Latest WebCardinal
        run: npm run get-source-code
        shell: bash

      - name: Release
        run: npm run release
        shell: bash

      - name: Archive
        run: zip -q -r webcardinal-release.zip ./release
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: webcardinal-release
          path: webcardinal-release.zip

#  upload-release:
#    needs: prepare-release
#
#    permissions: write-all
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: webcardinal-release
#
#      - name: Unzip archive
#        run: unzip -q webcardinal-release.zip
#        shell: bash
#
#      - name: Inspect distribution
#        run: cd ./release && ls -A
#
#      - name: Publish the new release
#        run: |
#          chmod +x .github/publish_release.sh
#          .github/publish_release.sh
#        env:
#          ACCESS_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        shell: bash

  upload-minimal-release:
    needs: prepare-release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: repository/webcardinal-minimal-release
          repository: webcardinal/webcardinal-minimal-release

      - uses: actions/download-artifact@v3
        with:
          name: webcardinal-release

      - name: Unzip archive
        shell: bash
        run: unzip -q webcardinal-release.zip

      - name: Prepare distribution
        shell: bash
        run: |
          cd repository/webcardinal-minimal-release
          rm -rf ./dist
          cp -r ../../release/production/bundle-minimal/* ./
          ls -R

      - name: Push to master branch
        run: |
          git config user.name Github Actions
          git config user.email github-actions@github.com
          git add dist/
          git commit -m "WebCardinal release for bundle-minimal (build-id $GITHUB_RUN_NUMBER)"
          git push
